version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: turbines

  api:
    image: leo5621/wind-turbine-api:latest
    ports:
      - '8000:8000'
    command: ["--host", "0.0.0.0", "--port", "8000"]
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: turbines


volumes:
  postgres: