on:
  workflow_dispatch:

jobs:
  dockerize:
    timeout-minutes: 10
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and push Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: leo5621/${{ github.event.repository.name }}:${{ github.sha }}, leo5621/${{ github.event.repository.name }}:latest
